application: testdemo
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.htm
  
- url: /static
  static_dir: static
  expiration: '1d'
  
- url: /css
  static_dir: static/css
  expiration: '1d' 

- url: /js
  static_dir: static/js
  expiration: '1d'   
  
- url: /img
  static_dir: static/img
  expiration: '1d'    
  
- url: /cors
  static_dir: static/cors
  expiration: '1d'     
  
- url: /.*
  script: main.app
